version: "3.3"

services:
  auth-service:
    image: auth-service:latest
    ports:
      - "5000:5000"
      - "8000:8000"
    environment:
      - POSTGRES_USERNAME=postgres
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DATABASE=auth
      - POSTGRES_HOSTNAME=postgres-db
      - HTTP_ADDRESS=:8000
      - GRPC_ADDRESS=:5000
    depends_on:
      - postgres-db
      
  chat-service:
    image: chat-service:latest
    ports:
      - "8080:8080"
    environment:
      - HTTP_ADDRESS=:8080
      - AUTH_ADDRESS=auth-service:5000
      - MONGO_URI=mongodb://mongo-db:27017

  postgres-db:
    image: postgres:alpine
    ports:
      - "5432:5432"
  
    environment:
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=auth

  mongo-db:
    image: mongo:latest 
    ports:
      - "27017:27017"
