# FROM golang:latest AS build

# WORKDIR /build
# COPY . .
# RUN go build -o bin/auth github.com/sina-am/social-media/internal/auth 


# FROM ubuntu:latest

# WORKDIR /app
# COPY --from=build /build/bin/auth /app/auth

# CMD ["/app/auth"]

FROM ubuntu:latest

WORKDIR /app
COPY ./bin/auth /app/auth
EXPOSE 80
EXPOSE 5000
CMD ["/app/auth"]