FROM golang:latest AS build

WORKDIR /build
COPY . .
RUN go build -o bin/chat github.com/sina-am/social-media/internal/chat 


FROM ubuntu:latest

WORKDIR /app
COPY --from=build /build/bin/chat /app/chat

CMD ["/app/chat"]